apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-api
spec:
  selector:
    matchLabels:
      app: bot-api
  template:
    metadata:
      labels:
        app: bot-api
    spec:
      containers:
        - name: bot-api
          image: bot-api:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: bot-api
spec:
  selector:
    app: bot-api
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
